import { cp, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runCheck } from '../src/commands/check.js';
import { runInit } from '../src/commands/init.js';
import { runSync } from '../src/commands/sync.js';
import { fixture } from './util.js';

describe('runCheck', () => {
  it('reports each bucket in text form', async () => {
    const result = await runCheck({ cwd: fixture('project-buckets') });
    expect(result.analysis.usedButUndocumented).toEqual([
      'BRACKET_VAR',
      'IMPORT_META_FLAG',
      'PORT',
    ]);
    expect(result.analysis.documentedButUnused).toEqual(['LEGACY_TOKEN', 'REDIS_URL']);
    expect(result.analysis.documentedButMissingLocally).toEqual(['REDIS_URL']);
    expect(result.exitCode).toBe(1); // undocumented vars present, default failOn
  });

  it('produces names-only JSON', async () => {
    const result = await runCheck({ cwd: fixture('project-buckets'), format: 'json' });
    const parsed = JSON.parse(result.output);
    expect(parsed.ok).toBe(false);
    expect(parsed.usedButUndocumented).toEqual(['BRACKET_VAR', 'IMPORT_META_FLAG', 'PORT']);
    expect(parsed.counts.documented).toBe(4);
  });

  it('honours --fail-on overrides', async () => {
    const none = await runCheck({ cwd: fixture('project-buckets'), failOn: [] });
    expect(none.exitCode).toBe(0);

    const onUnused = await runCheck({
      cwd: fixture('project-buckets'),
      failOn: ['unused'],
    });
    expect(onUnused.exitCode).toBe(1);
  });
});

describe('runSync (read-only fixtures)', () => {
  it('proposes placeholders for undocumented vars without reading .env', async () => {
    const result = await runSync({ cwd: fixture('project-buckets') });
    expect(result.toAdd).toEqual(['BRACKET_VAR', 'IMPORT_META_FLAG', 'PORT']);
    expect(result.proposedLines).toEqual(['BRACKET_VAR=', 'IMPORT_META_FLAG=', 'PORT=']);
    expect(result.written).toBe(false);
  });
});

describe('write commands (temp dir)', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), 'env-doctor-'));
    await cp(fixture('project-buckets'), dir, { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('sync --write appends placeholders to the example file', async () => {
    const result = await runSync({ cwd: dir, write: true });
    expect(result.written).toBe(true);

    const example = await readFile(path.join(dir, '.env.example'), 'utf8');
    expect(example).toContain('PORT=');
    expect(example).toContain('BRACKET_VAR=');
    // The appended placeholder must be empty — never a value copied from .env.
    expect(example).not.toMatch(/PORT=.+/);
  });

  it('sync --write with a placeholder uses that literal, never a real value', async () => {
    const result = await runSync({ cwd: dir, write: true, placeholder: 'changeme' });
    expect(result.written).toBe(true);
    const example = await readFile(path.join(dir, '.env.example'), 'utf8');
    expect(example).toContain('PORT=changeme');
  });

  it('init --write refuses to overwrite an existing file without --force', async () => {
    const result = await runInit({ cwd: dir, write: true });
    expect(result.written).toBe(false);
    expect(result.exitCode).toBe(1);
    expect(result.output).toMatch(/already exists/);
  });

  it('init --write --force scaffolds from code references', async () => {
    const result = await runInit({ cwd: dir, write: true, force: true });
    expect(result.written).toBe(true);
    expect(result.vars).toEqual([
      'API_KEY',
      'BRACKET_VAR',
      'DATABASE_URL',
      'IMPORT_META_FLAG',
      'PORT',
    ]);
    const example = await readFile(path.join(dir, '.env.example'), 'utf8');
    expect(example).toContain('API_KEY=');
    expect(example).toContain('Generated by env-doctor');
  });

  it('init --write creates a fresh file when none exists', async () => {
    await rm(path.join(dir, '.env.example'));
    const result = await runInit({ cwd: dir, write: true });
    expect(result.written).toBe(true);
    const example = await readFile(path.join(dir, '.env.example'), 'utf8');
    expect(example).toContain('PORT=');
  });
});

describe('destructuring detection (end to end)', () => {
  it('check reports destructured vars as undocumented', async () => {
    const result = await runCheck({ cwd: fixture('project-destructuring') });
    expect(result.analysis.usedButUndocumented).toEqual([
      'AWS_REGION',
      'DB_HOST',
      'DB_NAME',
      'DB_PORT',
      'VITE_PUBLIC_URL',
    ]);
  });
});

describe('init on a project with custom config', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), 'env-doctor-cfg-'));
    await writeFile(
      path.join(dir, 'app.js'),
      'const k = process.env.FOO; const j = os.environ["BAR"];',
      'utf8',
    );
    await writeFile(
      path.join(dir, '.envdoctorrc.json'),
      JSON.stringify({
        source: ['**/*.js'],
        patterns: ['os\\.environ\\[[\'"]([A-Za-z_][A-Za-z0-9_]*)[\'"]\\]'],
      }),
      'utf8',
    );
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('applies custom patterns from .envdoctorrc.json', async () => {
    const result = await runInit({ cwd: dir });
    expect(result.vars).toEqual(['BAR', 'FOO']);
  });
});
