import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadConfig, resolvePatterns } from '../config.js';
import { readEnvKeys } from '../io.js';
import { compilePatterns, scanSources } from '../scanner.js';

export interface InitOptions {
  cwd: string;
  configPath?: string;
  write?: boolean;
  force?: boolean;
  /** Overrides `config.placeholder` when provided. Never a real value. */
  placeholder?: string;
}

export interface InitResult {
  /** All variable names referenced in code (names only), sorted. */
  vars: string[];
  /** The generated `.env.example` content (placeholders only). */
  content: string;
  written: boolean;
  exampleFile: string;
  exitCode: number;
  output: string;
}

const HEADER = [
  '# Environment variables for this project.',
  '# Generated by env-doctor — fill in values in your local .env, never here.',
  '# Never commit real secrets.',
  '',
];

/**
 * Scaffold a `.env.example` from the variables referenced in code. Generated
 * values are placeholders only; env-doctor never reads or copies real values.
 */
export async function runInit(options: InitOptions): Promise<InitResult> {
  const config = await loadConfig({ cwd: options.cwd, configPath: options.configPath });
  const placeholder = options.placeholder ?? config.placeholder;
  const ignore = new Set(config.ignore);

  const patterns = compilePatterns(resolvePatterns(config));
  const { refs } = await scanSources({
    cwd: options.cwd,
    source: config.source,
    exclude: config.exclude,
    patterns,
  });

  const vars = [...new Set(refs.filter((name) => !ignore.has(name)))].sort((a, b) =>
    a.localeCompare(b),
  );

  const body = vars.map((name) => `${name}=${placeholder}`);
  const content = `${[...HEADER, ...body].join('\n')}\n`;

  const fullPath = path.resolve(options.cwd, config.exampleFile);
  const existing = await readEnvKeys(options.cwd, config.exampleFile);

  let written = false;
  let exitCode = 0;
  let output: string;

  if (!options.write) {
    output = renderPreview(config.exampleFile, vars, content);
  } else if (existing.exists && !options.force) {
    exitCode = 1;
    output = `✖  ${config.exampleFile} already exists. Use --force to overwrite, or run \`env-doctor sync\` to add only missing variables.`;
  } else {
    await writeFile(fullPath, content, 'utf8');
    written = true;
    output = `✔  Wrote ${config.exampleFile} with ${vars.length} variable${vars.length === 1 ? '' : 's'}.`;
  }

  return { vars, content, written, exampleFile: config.exampleFile, exitCode, output };
}

function renderPreview(exampleFile: string, vars: string[], content: string): string {
  if (vars.length === 0) {
    return 'env-doctor init — no environment-variable references found in source.';
  }
  return [
    `env-doctor init — ${vars.length} variable${vars.length === 1 ? '' : 's'} found`,
    '',
    `Proposed ${exampleFile}:`,
    '',
    content.trimEnd(),
    '',
    'Run again with --write to create the file.',
  ].join('\n');
}
